### ISSUE TITLE
[i915]] *ERROR* DC state mismatch (0x0 -> 0x2) / Freeze

### ISSUE THREAD

**Issue by nisenbeck** [nisenbeck/ct-server-2016-jessie#1]
Ab Kernel 4.8.6 tritt nach ca. 1,5 Stunden der Fehler "[drm:gen9_set_dc_state [i915]] *ERROR* DC state mismatch (0x0 -> 0x2)" auf. Dies betrifft auch Kernel 4.8.7.
dmesg Output: [DC state mismatch.txt](https://github.com/Bananian/ct-server-2016-jessie/files/587693/DC.state.mismatch.txt)

Dazu kommt es teilweise zu einem kompletten Freeze oder "nur" einem Eintrag im Log/dmesg.

Als temporärer Workaround kann der Kernel 4.8.4 verwendet werden, dieser ist nicht betroffen:
https://github.com/Bananian/ct-server-2016-jessie/tree/master/deb

Ich arbeite bereits zusammen mit @bullet64 an einer Lösung.

**Comment by nisenbeck** [comment]
Ich habe den Kernel 4.8.4 nachträglich zum Repository hinzugefügt. Installierbar über das Paket "linux-image-4.8.4-skylake"

**Comment by nisenbeck** [comment]
Der Fehler wird offenbar durch das Paket "firmware-misc-nonfree" und zwar konkret durch die Intel i915 Firmware verursacht. Ohne die Firmware läuft der Kernel problemlos.

Ich rate dazu dieses Paket zu deinstallieren oder sicherzustellen, dass die Firmware aus dem Ordner /lib/firmware/i915 nicht geladen wird.

**Comment by leezu** [comment]
Auf einer [anderen Skylake Plattform](http://www.notebookcheck.net/Xiaomi-Mi-Air-13-3-inch-Notebook-Review.180561.0.html) tritt bei mir zur Zeit das gleiche Problem auf. Habt ihr die Regression upstream gemeldet? 

Für andere, [dieser Blogpost](https://frank-mankel.de/kategorien/projekt-nas/208-projekt-nas-kernel-4-8-7-repo) nimmt auch auf den Fehler Bezug.

**Comment by foobarth** [comment]
"Confirmed" auch unter Arch Linux mit Kernel 4.9.11. Maschine (D3417-B, Pentium G4500) läuft erst stabil wenn die i915 firmware nicht geladen wird. Da unter Arch das Paket als Dependency des Kernels zwingend installiert werden muss, musste ich das Verzeichnis umbenennen und die initrd neu erzeugen. Seither ist "Ruhe".

Daher noch mal die Frage: wurde es upstream gemeldet? Hat jemand nähere Infos ?

Evtl. könnte man über i915 Modulparameter das fehlerhafte Feature abschalten und die Firmware trotzdem verwenden.

`$ modinfo i915`

**Comment by FrankM64** [comment]
Nico ist im Urlaub, weiß nicht ob er hier aktuell mit liest. Werde ihn aber dran erinnern ;)

**Comment by nisenbeck** [comment]
Moin,
bin wieder zurück in Hamburg :-)

Bisher habe ich nichts Upstream reportet, da wir die Firmware für unseren Einsatzzweck nicht wirklich benötigen. Da das Problem aber offenbar ein generelles ist, sollten wir es dann doch mal melden.

Grüße,
Nico

**Comment by leezu** [comment]
Alles klar. Kannst du den Link zum Bugreport dann hier eintragen? Ggfs. können andere dann noch weitere Informationen dazutragen

**Comment by foobarth** [comment]
Ich das ganze mal bei Arch reported, wo es auf "upstream" gesetzt wurde. https://bugs.archlinux.org/task/53227

**Comment by leezu** [comment]
Ich denke, dass das auf "upstream" setzen nur bedeutet dass Arch nicht zuständig ist. Upstream reporten müsstest du es noch. Schau mal hier: https://www.kernel.org/pub/linux/docs/lkml/reporting-bugs.html

Am Besten solltest du dafür aber einmal den aktuellen Kernel (4.10.3) selber kompilieren und testen ob der Bug dort noch auftritt.

Bei meinem Problem scheint es um einen anderen Bug zu gehen, da mein System auf Intel Broadwell läuft.

**Comment by moritzthecat** [comment]
hatte merkwürdige Abstürze, die ich jetzt auf dieses Problem zurückführen konnte - Danke für den Thread. 

Mein System: Openmedivault mit Jessie 4.9.0-0.bpo.3-amd64
gehe jetzt zurück auf 4.8.0-0.bpo.2-amd64 - hoffe dass die Abstürze dann aufhören.

Gibt es einen workaround, wie man das i915 Modul mit 4.9 weiter nutzen kann oder gibt es gar ein update ?

**Comment by nisenbeck** [comment]
Wenn sich jemand bereit erklärt zu testen, würde ich mal ein Linux 4.11 Paket kompilieren.

Interesse?

**Comment by FrankM64** [comment]
Ist das denn immer noch nicht fertig? Gib her, ich hab morgen Zeit ;)

**Comment by nisenbeck** [comment]
Hier ein Linux 4.11 Paket zum Testen:
https://github.com/nisenbeck/ct-server-2016-jessie/raw/master/deb/linux-image-4.11.5-skylake_4.11.5-1_amd64.deb

Bitte herunterladen, installieren (dpkg -i ...) und das Paket firmware-misc-nonfree installieren. Nach einem Neustart beobachten, ob der Fehler weiterhin auftritt.

Danke!

**Comment by FrankM64** [comment]
Installiert, läuft so weit. Ein paar Fehler im Log, aber die Deutung überlasse ich den Profi's. Danke!

**Comment by moritzthecat** [comment]
gerade 2x hintereinander zugeschlagen mit backport kernel
Linux 4.8.0-0.bpo.2-amd64 #1 SMP Debian **4.8.15**-2~bpo8+2 (2017-01-17) x86_64 GNU/Linux
Ist lange her, dass ich das letzte Mal einen Kernel gebaut habe...
Geht die Anleitung auch, wenn man den backport kernel benötigt (ich nutze Openmediavault).

**Comment by nisenbeck** [comment]
Die Anleitung sollte grundsätzlich auf allen Debian Derivaten funktionieren (also auch z.B. Ubuntu).
Hast du mal mein Linux 4.11 Kernel Paket (siehe oben) ausprobiert? Wofür brauchst du den Backport Kernel (4.8)?

**Comment by moritzthecat** [comment]
Openmediavault (OMV) verwendet Debian Jessie und nur ausgesuchte (festverdrahtete) backport kernel. Das ZFS plugin ist in Entwicklung und liess sich in der Vergangenheit nur mit passeder Konfiguration aus Extras Plug-in und Kernel installieren. Zur Zeit ist 4.9 der aktuellste unterstützte Kernel.

**Comment by moritzthecat** [comment]
Wie erwartet zickt DKMS rum das zfs modul in 4.11 zu bauen... passt jetzt wahrscheinlich nicht mit dem Rest zusammen.
```
Error! Bad return status for module build on kernel: 4.11.5-skylake (x86_64)
Consult /var/lib/dkms/spl/0.6.5.9/build/make.log for more information.
```

**Comment by nisenbeck** [comment]
Ah, okay. Der Punkt mit ZFS Support war mir neu - danke für die Info!
Ich kenne mich leider mit OMV zu wenig aus als dass ich da jetzt "mal eben" nachschauen könnte oder gar einen neuen Kernel mit ZFS kompilieren kann.

**Comment by moritzthecat** [comment]
Ja, war mir zunächst nicht klar, dass das eine Abhängigkeit sein könnte. Ich bin zurück auf 4.9 und habe ein verfügbares update vom 14. Juni eingespielt.
`4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2~bpo8+1 (2017-06-14) x86_64 GNU/Linux
 und zugehörige firmware-misc-nonfree 20161130-2~bpo8+1 `
Seit 3h kein crash - wo könnte ich nachschauen, ob das update den Fehler behoben hat?
Hier bin ich nicht fündig geworden:
[(https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=stable;package=+linux-headers-4.9.0-0.bpo.3-amd64;package=firmware-misc-nonfree)](url)

**Comment by foobarth** [comment]
ZFS auf Kernel 4.11+ wird erst seit 0.6.5.10 unterstützt: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.10 - ich habe 4.11 unter Arch laufen, aber nach wie vor die Abstürze mir der installierten Firmware.

**Comment by moritzthecat** [comment]
leider keine Besserung ... 
kern.log:Jun 27 12:27:51 <machine> kernel: [234723.532753] [drm:gen9_set_dc_state [i915]] *ERROR* DC state mismatch (0x0 -> 0x2)

Habe jetzt die i915 firmware deinstalliert [wie hier beschrieben](https://frank-mankel.de/kategorien/projekt-nas/208-projekt-nas-kernel-4-8-7-repo).

Wie bekomme ich mit, dass das Problem behoben wurde ?
