### ISSUE TITLE
Random Shutdown/freeze

### ISSUE THREAD

**Issue by ManuGithubSteam** [nisenbeck/ct-server-2016-jessie#3]
Hi

Seit ich den Bananian Kernel und den habe. kommt es nach kurzer Zeit zu einem Freeze der Verbindung zum server. Die Platten scheinen dann auch im Standby zu sein. Den Realtek treiber habe ich bsi jetzt noch nicht drauf gehabt, weil der mit linux-firmware konflikt hat. Ich werde den jetzt mal installieren und dann weiter sehen....

Konntet ihr sowas auch beobachten ?

Viele Grüße

Manuel

**Comment by nisenbeck** [comment]
Hey,

hast du das Paket "firmware-misc-nonfree" installiert? Wenn ja bitte entfernen.

Grüße und ein schönes Wochenende!
Nico

**Comment by ManuGithubSteam** [comment]
Hallo Nico,

Nein das ist nicht installiert.

Also ich glaube es liegt eher am Netzwerk. Der Server lief heute (die
platten habe ich gehört) aber ich konnte nicht mit ssh drauf und der
Router hat den Server nicht als verbunden angezeigt (mit LAN).

Erst nach einem kaltstart des Servers wurde er wieder erkannt.

Ich hatte vorher noch nicht den Realteak treiber drauf, sondern nur den
normalen von linux-firmware.

Beim installieren musste ich --force angeben. Sollte ich das
linux-firmware paket deinstallieren ?

Viele Grüße

Manuel

**Comment by nisenbeck** [comment]
Hey Manuel,

poste doch mal bitte den Output von folgenden Befehlen nach einigen Stunden Betrieb:
lsmod | grep r81
dmesg

Ich habe das linux-firmware Paket nicht installiert und verwende den r8169 für Ethernet. Ohne Probleme.

Grüße,
Nico

**Comment by ManuGithubSteam** [comment]
Hi Nico,

Danke für die schnelle Antwort, Werde das machen :-)

Habe jetzt auch mal auf 9.3 geupdated und das linux-fimrware paket
runter geworfen.

Grüße

**Comment by nisenbeck** [comment]
Ich schließe diesen Issue mal. Hat ja offenbar geholfen ;-)
