### ISSUE TITLE
Upgrade auf Debian Stretch

### ISSUE THREAD

**Issue by ghost** [nisenbeck/ct-server-2016-jessie#6]
Was gilt es zu beachten nachdem der Server auf Debian Stretch hochgerüsted wurde?
Genügt es das Backport repository anzupassen?

**Comment by nisenbeck** [comment]
Das Repository für den custom 4.9er Kernel (/etc/apt/sources.list.d/ct-server-2016-jessie.list) ist ebenfalls nicht mehr nötig. Stretch bringt den 4.9er Kernel bereits mit.

Hast du schon aktualisiert? Welcher Kernel läuft jetzt bei dir?
Ich werde das mal in einer VM testen und Hinweise zum Upgrade auf Debian 9 geben.

**Comment by ghost** [comment]
Upgrade auf Stretch hat relativ schmerzlos geklappt [mit dieser Anleitung](https://linuxconfig.org/how-to-upgrade-debian-8-jessie-to-debian-9-stretch). Kernel Version ist `4.9.26-skylake`.
Die einzige Anpassung war bei Samba nötig, da mein SONOS nur SMBv1 unterstützt, welche mit dem Upgrade deaktiviert wurde.

**Comment by nisenbeck** [comment]
Hier die vollständige Anleitung inklusive dem Wechsel auf den offiziellen Debian Kernel: https://github.com/nisenbeck/ct-server-2016-jessie/blob/master/STRETCH_UPGRADE.md
